osx_image: xcode9.2
os: osx
sudo: required
language: js
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
before_cache:
- rm -rf node_modules/.yarn-integrity
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
install:
- nvm install 9
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- yarn global add xvfb-maybe
- yarn
script:
- yarn ci
- util_scripts/check-headers.sh
before_deploy:
- bash util_scripts/travis-number.sh
- FORCE_DOWNLOAD=1 yarn download:bins
- yarn build
- mkdir binaries && mkdir releases
- cp build/Mysterion-*.dmg binaries/Mysterion-latest.dmg
- cp build/Mysterion-*.dmg releases/
deploy:
  # Latest (master branch)
  - provider: pages
    edge:
      branch: v1.8.47
    local-dir: binaries
    skip-cleanup: true
    github-token: "$GITHUB_API_TOKEN"
    keep-history: false
    # Example: mysterion_osx
    target-branch: mysterion_$TRAVIS_OS_NAME
    repo: MysteriumNetwork/build-artifacts
    on:
      tags: false
      branch: master
  # Release-candidate ('x.x' release branches)
  - provider: pages
    edge:
      branch: v1.8.47
    local-dir: releases
    skip-cleanup: true
    github-token: "$GITHUB_API_TOKEN"
    keep-history: false
    # Example: mysterion_osx_rc
    target-branch: mysterion_${TRAVIS_OS_NAME}_rc
    repo: MysteriumNetwork/build-artifacts
    on:
      tags: false
      all_branches: true
      conditions: $TRAVIS_BRANCH =~ ^[0-9]+\.[0-9]+$
  # Release (tags)
  - provider: releases
    file_glob: true
    file: releases/*
    skip_cleanup: true
    api_key: "$GITHUB_API_TOKEN"
    on:
      tags: true

notifications:
  slack:
    rooms:
      - secure: >
          MRTSnzKnwmkxR4yz74eT6Cp1lyIZjlAvRssiaFr+OmtQcQlRmmCayKeUSygvaUHrNQgLuc5dzv1DKsdSb/qAE0To+3C3VE+wrZvtw+KyrYIzxG
          GQdcNviP5DaTqNo1ah15Vw5Cac823F6K7HIDgBpj2u8dN4R/JEtL52dY8MSRXIGu5IBqxDOA0gpQa+lP4UzRCRo3dx8PvisCx9JhPR0AoPjDOp
          luXZjigB5qtqrzB7XczvUXJVMdTm6YXyBT1R3xyQri/77RVEPB/LHFMxNl/ntDVQUb8Wyw+Oyc/mbRjbbNdPaWZAsVqkdUy7f49ZPg91Ja+wwr
          L5waUkwiYjeVe/cHLwSVaiAhCS51li0ura1CLKMxF6kBohy6GnRMdJlUE4Yf54uCECKpA+4YVFyCC1/E0h1D6kIvDxpa/mqven2oQwBoh7jz27
          JIsTVPlMF/b1swlL+Bt5zqxx+IHyrDmIylLyWhMBBtZ4IO5JLgXP9RIP5Bd/CPfFQcdB13/fN1y8cOP6V7aK4Yjoa3NA0MLeHkZx5JeP1lgtrn
          IdM3dB9yo4qiA3y+qzPo8fawW715HRHNlgLnWtT5fAswEECDLCQnUaFLAzrVQmpQXuGK3hJHvBIEjh/NLbQsJ6OVzDGc4kthZSVU2Uq516KiD5
          7aGX4NEmu2sFxuuYdiyhaBU=
    on_success: change
    on_failure: always
